---
- name: Check if Pi-hole is installed
  stat:
    path: /usr/local/bin/pihole
  register: pihole_installed

- name: Ensure /etc/pihole directory exists
  file:
    path: /etc/pihole
    state: directory
    mode: "0755"

- name: Create setupVars.conf
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    mode: "0644"
  when: not pihole_installed.stat.exists

- name: Download Pi-hole installer
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole_install.sh
    mode: "0755"
  when: not pihole_installed.stat.exists

- name: Install Pi-hole
  command: "/tmp/pihole_install.sh --unattended"
  when: not pihole_installed.stat.exists
  notify:
    - Restart Pi-hole
    - Test Pi-hole configuration

- name: Update Pi-hole if installed
  command: "pihole -up"
  when: pihole_installed.stat.exists
  notify:
    - Restart Pi-hole
    - Test Pi-hole configuration

- name: Create custom DNS entries
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
    mode: "0644"
    backup: true
  notify:
    - Restart Pi-hole
    - Test Pi-hole configuration
